a = input('Digite algo: ')
print('A classe do que você escreveu é: {}'.format(type(a)))
cores = {'limpa': '\033[m', 'verde': '\033[1;32m', 'vermelho': '\033[1;31m', 'amarelo': '\033[1;33m'}
print(f'Is {cores['verde']}al{cores['limpa']}{cores['vermelho']}num{cores['limpa']}:', a.isalnum())
print(f'Is {cores['verde']}alpha{cores['limpa']}:', a.isalpha())
print(f'Is {cores['verde']}space{cores['limpa']}:', a.isspace())
print(f'Is {cores['verde']}title{cores['limpa']}:', a.istitle())
print(f'Is {cores['verde']}upper{cores['limpa']}:', a.isupper())
print(f'Is {cores['verde']}lower{cores['limpa']}:', a.islower())
print(f'Is {cores['vermelho']}numeric{cores['limpa']}:', a.isnumeric())
print(f'Is {cores['vermelho']}decimal{cores['limpa']}:', a.isdecimal())
print(f'Is {cores['vermelho']}digit{cores['limpa']}:', a.isdigit())
print(f'Is {cores['amarelo']}printable{cores['limpa']}:', a.isprintable())
print(f'Is {cores['amarelo']}ascii{cores['limpa']}:', a.isascii())
print(f'Is {cores['amarelo']}identifier{cores['limpa']}:', a.isidentifier())
